#!/bin/bash
# This script is used for running the tests with proper arguments
# from within Jenkins

set -e
set -u
set -x

if [ -d /results ] ; then
  # Running from Jenkins (RW)
  RESULTS="/results"
  cd "/code"
else
  # Running locally in Docker
  RESULTS="./results"
  mkdir -p "${RESULTS}"
fi

busted -o junit > ${RESULTS}/test_busted.xml
